GET http://0.0.0.0:8787/api/posts/blah/comments

###
POST http://0.0.0.0:8787/api/posts/blah/comments
Content-Type: application/json

{
  "author": "Pasha", "body": "Some comment"
}

###
GET https://cf-comments.kleshney.workers.dev/api/posts/blah/comments

###
POST https://cf-comments.kleshney.workers.dev/api/posts/blah/comments
Content-Type: application/json

{
  "author": "anonymous", "body": "Does it even work?"
}
