name = "cf-comments"
main = "src/index.ts"
compatibility_date = "2022-11-27"

[[ d1_databases ]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "comments-db"
database_id = "91e6081a-50b9-4e4b-a3b3-bd00967f713b"