name = "cf-comments"
main = "build/js/packages/cf-comments/kotlin/cf-comments.js"
compatibility_date = "2022-11-27"

[vars]
API_TOKEN = "example_dev_token"

[[ d1_databases ]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "comments-db"
database_id = "91e6081a-50b9-4e4b-a3b3-bd00967f713b"